/** profile：原生 Canvas 头像裁剪器 */
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
export function AvatarCropper({ file, onCancel, onComplete }: { file: File | null; onCancel: () => void; onComplete: (blob: Blob) => void }) {
  const canvas = useRef<HTMLCanvasElement>(null); const [image, setImage] = useState<HTMLImageElement | null>(null); const [scale, setScale] = useState(1); const [drag, setDrag] = useState({ x: 0, y: 0 }); const start = useRef<{ x: number; y: number } | null>(null);
  useEffect(() => { if (!file) return; const url = URL.createObjectURL(file); const next = new Image(); next.onload = () => setImage(next); next.src = url; return () => URL.revokeObjectURL(url); }, [file]);
  useEffect(() => { const target = canvas.current; if (!target || !image) return; const context = target.getContext("2d"); if (!context) return; const source = Math.min(image.naturalWidth, image.naturalHeight) / scale; context.clearRect(0, 0, 512, 512); context.drawImage(image, (image.naturalWidth - source) / 2 - drag.x, (image.naturalHeight - source) / 2 - drag.y, source, source, 0, 0, 512, 512); }, [image, scale, drag]);
  function complete() { canvas.current?.toBlob((blob) => blob && onComplete(blob), "image/webp", 0.9); }
  return <Dialog open={Boolean(file)} onOpenChange={(open) => !open && onCancel()}><DialogContent><DialogHeader><DialogTitle>裁剪头像</DialogTitle></DialogHeader><canvas ref={canvas} width={512} height={512} className="mx-auto w-full max-w-sm cursor-move rounded-full" onPointerDown={(event) => { start.current = { x: event.clientX, y: event.clientY }; event.currentTarget.setPointerCapture(event.pointerId); }} onPointerMove={(event) => { if (!start.current) return; setDrag((current) => ({ x: current.x + event.clientX - start.current!.x, y: current.y + event.clientY - start.current!.y })); start.current = { x: event.clientX, y: event.clientY }; }} onPointerUp={() => { start.current = null; }} /><input aria-label="头像缩放" type="range" min="1" max="3" step="0.05" value={scale} onChange={(event) => setScale(Number(event.target.value))} /><DialogFooter><Button variant="outline" onClick={onCancel}>取消</Button><Button onClick={complete}>使用此头像</Button></DialogFooter></DialogContent></Dialog>;
}
