/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FocusRouteRouteImport } from './routes/_focus/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedInterviewHubRouteImport } from './routes/_authenticated/interview-hub'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedResumesIndexRouteImport } from './routes/_authenticated/resumes/index'
import { Route as AuthenticatedBankIndexRouteImport } from './routes/_authenticated/bank/index'
import { Route as FocusVoiceNewRouteImport } from './routes/_focus/voice.new'
import { Route as AuthenticatedSessionIdRouteImport } from './routes/_authenticated/session.$id'
import { Route as AuthenticatedResumesIdRouteImport } from './routes/_authenticated/resumes/$id'
import { Route as AuthenticatedReportIdRouteImport } from './routes/_authenticated/report.$id'
import { Route as AuthenticatedLegacyIdRouteImport } from './routes/_authenticated/legacy.$id'
import { Route as AuthenticatedBankIdRouteImport } from './routes/_authenticated/bank/$id'
import { Route as FocusVoiceSessionIdRouteImport } from './routes/_focus/voice.session.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRouteRoute = FocusRouteRouteImport.update({
  id: '/_focus',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewHubRoute =
  AuthenticatedInterviewHubRouteImport.update({
    id: '/interview-hub',
    path: '/interview-hub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumesIndexRoute =
  AuthenticatedResumesIndexRouteImport.update({
    id: '/resumes/',
    path: '/resumes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBankIndexRoute = AuthenticatedBankIndexRouteImport.update({
  id: '/bank/',
  path: '/bank/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FocusVoiceNewRoute = FocusVoiceNewRouteImport.update({
  id: '/voice/new',
  path: '/voice/new',
  getParentRoute: () => FocusRouteRoute,
} as any)
const AuthenticatedSessionIdRoute = AuthenticatedSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumesIdRoute = AuthenticatedResumesIdRouteImport.update({
  id: '/resumes/$id',
  path: '/resumes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportIdRoute = AuthenticatedReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLegacyIdRoute = AuthenticatedLegacyIdRouteImport.update({
  id: '/legacy/$id',
  path: '/legacy/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankIdRoute = AuthenticatedBankIdRouteImport.update({
  id: '/bank/$id',
  path: '/bank/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FocusVoiceSessionIdRoute = FocusVoiceSessionIdRouteImport.update({
  id: '/voice/session/$id',
  path: '/voice/session/$id',
  getParentRoute: () => FocusRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/interview-hub': typeof AuthenticatedInterviewHubRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/new': typeof AuthenticatedNewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/bank/$id': typeof AuthenticatedBankIdRoute
  '/legacy/$id': typeof AuthenticatedLegacyIdRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/resumes/$id': typeof AuthenticatedResumesIdRoute
  '/session/$id': typeof AuthenticatedSessionIdRoute
  '/voice/new': typeof FocusVoiceNewRoute
  '/bank/': typeof AuthenticatedBankIndexRoute
  '/resumes/': typeof AuthenticatedResumesIndexRoute
  '/voice/session/$id': typeof FocusVoiceSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/interview-hub': typeof AuthenticatedInterviewHubRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/new': typeof AuthenticatedNewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/bank/$id': typeof AuthenticatedBankIdRoute
  '/legacy/$id': typeof AuthenticatedLegacyIdRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/resumes/$id': typeof AuthenticatedResumesIdRoute
  '/session/$id': typeof AuthenticatedSessionIdRoute
  '/voice/new': typeof FocusVoiceNewRoute
  '/bank': typeof AuthenticatedBankIndexRoute
  '/resumes': typeof AuthenticatedResumesIndexRoute
  '/voice/session/$id': typeof FocusVoiceSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_focus': typeof FocusRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/interview-hub': typeof AuthenticatedInterviewHubRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/bank/$id': typeof AuthenticatedBankIdRoute
  '/_authenticated/legacy/$id': typeof AuthenticatedLegacyIdRoute
  '/_authenticated/report/$id': typeof AuthenticatedReportIdRoute
  '/_authenticated/resumes/$id': typeof AuthenticatedResumesIdRoute
  '/_authenticated/session/$id': typeof AuthenticatedSessionIdRoute
  '/_focus/voice/new': typeof FocusVoiceNewRoute
  '/_authenticated/bank/': typeof AuthenticatedBankIndexRoute
  '/_authenticated/resumes/': typeof AuthenticatedResumesIndexRoute
  '/_focus/voice/session/$id': typeof FocusVoiceSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/interview-hub'
    | '/knowledge'
    | '/new'
    | '/settings'
    | '/bank/$id'
    | '/legacy/$id'
    | '/report/$id'
    | '/resumes/$id'
    | '/session/$id'
    | '/voice/new'
    | '/bank/'
    | '/resumes/'
    | '/voice/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/interview-hub'
    | '/knowledge'
    | '/new'
    | '/settings'
    | '/bank/$id'
    | '/legacy/$id'
    | '/report/$id'
    | '/resumes/$id'
    | '/session/$id'
    | '/voice/new'
    | '/bank'
    | '/resumes'
    | '/voice/session/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_focus'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/interview-hub'
    | '/_authenticated/knowledge'
    | '/_authenticated/new'
    | '/_authenticated/settings'
    | '/_authenticated/bank/$id'
    | '/_authenticated/legacy/$id'
    | '/_authenticated/report/$id'
    | '/_authenticated/resumes/$id'
    | '/_authenticated/session/$id'
    | '/_focus/voice/new'
    | '/_authenticated/bank/'
    | '/_authenticated/resumes/'
    | '/_focus/voice/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  FocusRouteRoute: typeof FocusRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_focus': {
      id: '/_focus'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FocusRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview-hub': {
      id: '/_authenticated/interview-hub'
      path: '/interview-hub'
      fullPath: '/interview-hub'
      preLoaderRoute: typeof AuthenticatedInterviewHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumes/': {
      id: '/_authenticated/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof AuthenticatedResumesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank/': {
      id: '/_authenticated/bank/'
      path: '/bank'
      fullPath: '/bank/'
      preLoaderRoute: typeof AuthenticatedBankIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_focus/voice/new': {
      id: '/_focus/voice/new'
      path: '/voice/new'
      fullPath: '/voice/new'
      preLoaderRoute: typeof FocusVoiceNewRouteImport
      parentRoute: typeof FocusRouteRoute
    }
    '/_authenticated/session/$id': {
      id: '/_authenticated/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof AuthenticatedSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumes/$id': {
      id: '/_authenticated/resumes/$id'
      path: '/resumes/$id'
      fullPath: '/resumes/$id'
      preLoaderRoute: typeof AuthenticatedResumesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/$id': {
      id: '/_authenticated/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof AuthenticatedReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/legacy/$id': {
      id: '/_authenticated/legacy/$id'
      path: '/legacy/$id'
      fullPath: '/legacy/$id'
      preLoaderRoute: typeof AuthenticatedLegacyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank/$id': {
      id: '/_authenticated/bank/$id'
      path: '/bank/$id'
      fullPath: '/bank/$id'
      preLoaderRoute: typeof AuthenticatedBankIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_focus/voice/session/$id': {
      id: '/_focus/voice/session/$id'
      path: '/voice/session/$id'
      fullPath: '/voice/session/$id'
      preLoaderRoute: typeof FocusVoiceSessionIdRouteImport
      parentRoute: typeof FocusRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedInterviewHubRoute: typeof AuthenticatedInterviewHubRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedBankIdRoute: typeof AuthenticatedBankIdRoute
  AuthenticatedLegacyIdRoute: typeof AuthenticatedLegacyIdRoute
  AuthenticatedReportIdRoute: typeof AuthenticatedReportIdRoute
  AuthenticatedResumesIdRoute: typeof AuthenticatedResumesIdRoute
  AuthenticatedSessionIdRoute: typeof AuthenticatedSessionIdRoute
  AuthenticatedBankIndexRoute: typeof AuthenticatedBankIndexRoute
  AuthenticatedResumesIndexRoute: typeof AuthenticatedResumesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedInterviewHubRoute: AuthenticatedInterviewHubRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedBankIdRoute: AuthenticatedBankIdRoute,
  AuthenticatedLegacyIdRoute: AuthenticatedLegacyIdRoute,
  AuthenticatedReportIdRoute: AuthenticatedReportIdRoute,
  AuthenticatedResumesIdRoute: AuthenticatedResumesIdRoute,
  AuthenticatedSessionIdRoute: AuthenticatedSessionIdRoute,
  AuthenticatedBankIndexRoute: AuthenticatedBankIndexRoute,
  AuthenticatedResumesIndexRoute: AuthenticatedResumesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface FocusRouteRouteChildren {
  FocusVoiceNewRoute: typeof FocusVoiceNewRoute
  FocusVoiceSessionIdRoute: typeof FocusVoiceSessionIdRoute
}

const FocusRouteRouteChildren: FocusRouteRouteChildren = {
  FocusVoiceNewRoute: FocusVoiceNewRoute,
  FocusVoiceSessionIdRoute: FocusVoiceSessionIdRoute,
}

const FocusRouteRouteWithChildren = FocusRouteRoute._addFileChildren(
  FocusRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  FocusRouteRoute: FocusRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
